export const generalLeaderBoardData = [
  {
    rank: 1,
    name: "Jameslee201",
    image: "https://picsum.photos/id/1/200",
    actPts: "8,242",
        multiplier: "4x",
  },
  {
    rank: 2,
    name: "Sameslee201",
    image: "https://picsum.photos/id/2/200",
    actPts: "8,242",
        multiplier: "1x",
  },
  {
    rank: 3,
    name: "Shaameslee201",
    image: "https://picsum.photos/id/3/200",
    actPts: "8,200",
        multiplier: "10x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "11,642",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "11,642",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "11,642",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "11,642",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "11,642",
  },
];
export const campaignLeaderBoardData = [
  {
    rank: 1,
    name: "Daniel3402",
    image: "https://picsum.photos/id/10/200",
    actPts: "8,242",
        multiplier: "20x",
  },
  {
    rank: 2,
    name: "boomeslee201",
    image: "https://picsum.photos/id/22/200",
    actPts: "9,242",
        multiplier: "16x",
  },
  {
    rank: 3,
    name: "Jacoee201",
    image: "https://picsum.photos/id/32/200",
    actPts: "81,200",
        multiplier: "11x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "2x",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "11,642",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "11,642",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "11,642",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "11,642",
  },
  {
    rank: 4,
    name: "Liksaslee01",
    image: "https://picsum.photos/id/4/200",
    actPts: "8,700",
        multiplier: "11,642",
  },
];